---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_prompt: yes
configure_python: yes
configure_vim: yes
configure_fonts: yes
configure_macos: yes
mas_installed_apps: yes

# Install dotfiles from a git repo
dotfiles_repo: https://github.com/bmacauley/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .bash_prompt
  - .editorconfig
  - .functions
  - .gitconfig
  - .gitignore
  - .hushlogin
  - .macos
  - .paths
  - .tmux.conf
  - .vim
  - .vimrc
  - .tmux.conf
  - .zprofile
  - .zshrc
  - .zsh_prompt


# Install/upgrade homebrew packages/taps/casks
homebrew_upgrade_all_packages: yes

homebrew_uninstalled_packages:

homebrew_installed_packages:
  - ack
  - awscli
  - aws-shell
  # - ansible # Installed via Pip.
  - autoconf
  - autojump
  - awsebcli
  - bash
  - bash-completion
  - battery
  # - bazel java issues
  - bfg
  - brew-cask-completion
  - buck
  - bundler-completion
  - cloc
  - cowsay
  - cookiecutter
  - ctags
  - curl
  - direnv
  - docker
  - docker-clean
  - docker-compose
  - docker-gen
  - docker-machine
  - docker-swarm
  - dos2unix
  - duti
  - enca
  - fasd
  - fish
  - freetds
  - gdbm
  - geoip
  - gettext
  - gist
  - git
  - git-crypt
  - git-flow
  - github-release
  - git-subrepo
  - gitup
  - glide
  - go
  - gpg
  - gpg2
  - gradle
  - gradle-completion
  - hub
  - heroku
  - heroku-toolbelt
  - htop-osx
  - httpie
  - hugo
  - ipcalc
  - iperf
  - jq
  - keychain
  - kitchen-completion
  - kops
  - launchctl-completion
  - libevent
  - libffi
  - libvterm
  - libxml2
  - libyaml
  - lynis
  - macvim
  - mas
  - maven
  - mcrypt
  - md5sha1sum
  - mercurial
  - mobile-shell
  - mtr
  - multitail
  - mysql
  - nmap
  - node
  - nomad
  - npm
  - nvm
  - nginx
  - mas
  - openssl
  - openvpn
  - osquery
  - p7zip
  - packer
  - packer-completion
  - pandoc
  - parallel
  - pip-completion
  - postgresql
  - pup
  - pv
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - python
  - python@2
  - rails-completion
  - rake-completion
  - ruby-completion
  - rancher-cli
  - rancher-compose
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - ruby
  - s3cmd
  - saltstack
  - scons
  - sshuttle
  - spark
  - sqlite
  - ssh-copy-id
  - stunnel
  - tccutil
  - terraform
  - terraform-docs
  - terragrunt
  - the_platinum_searcher
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - unixodbc
  - udptunnel
  - vagrant-completion
  - vault
  - vim
  - wget
  - wireguard-go
  - wireguard-tools
  - wrk
  - zeromq
  - z
  - zoomus
  - zsh
  - zsh-completions

homebrew_taps:
  - homebrew/core
  # - caskroom/cask
  - Goles/battery
  - facebook/fb

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
#  - alfred
#  - amazon-workdocs
#  - amazon-workspaces
  - atom
#  - caffeine
#  - charles
#  - clipy
#  - coconutbattery
#  - cyberduck
  - docker
#  - dropbox
#  - fantastical
  - firefox
#  - flux
#  - gas-mask
#  - gitter
#  - gitkraken
#  - github-desktop
  - google-chrome
  - google-drive
  - google-hangouts
  - gpgtools
 # - handbrake
#  - intellij-idea
  - iterm2
  - istat-menus
  - java
  - jetbrains-toolbox
#  - jump-desktop
#  - joinme
  - keybase
  - kitematic
  - kindle
#  - limechat
#  - omnigraffle
#  - outline-manager
  - pgadmin4
  - postico
  - postman
#  - powershell
#  - pycharm
#  - sequel-pro
#  - shadowsocks-libev
#  - shadowsocksx
  # - shadowsocksx-ng
#  - skitch
  - slack
#  - sourcetree
#  - sublime-text
  - tomighty
#  - transmit
  - tunnelblick
  - vagrant
  - virtualbox
  - visual-studio-code
  - wifi-explorer
#  - vlc


# Vim config
vundle_repo: https://github.com/gmarik/Vundle.vim.git
vundle_repo_accept_hostkey: yes


# Prompt config
# bash_git_prompt_repo: https://github.com/bmacauley/bash-git-prompt.git
# bash_git_prompt_repo_accept_hostkey: yes
zsh_git_prompt_repo: https://github.com/bmacauley/zsh-git-prompt.git
zsh_git_prompt_repo_accept_hostkey: yes

# Powerline fonts
powerline_fonts_repo: https://github.com/powerline/fonts.git
powerline_fonts_repo_version: 2015-12-04
powerline_fonts_repo_accept_hostkey: yes

# Install/Update Mac App store apps using MAS
mas_installed_app_ids:
      - 497799835 # Xcode (8.1)
#      - 824183456 # Affinity Photo (purchase)
      - 405399194 # Kindle
#      - 824171161 # Affinity Designer (purchase)
#      - 407963104 # Pixelmator (purchase)
#      - 937984704 # Amphetamine
#      - 441258766 # Magnet
#      - 524141863 # Jump Desktop (purchase)
      - 1295203466 # Microsoft Remote Desktop v10
#      - 441258766 # Magnet (purchase)
      - 406056744 # Evernote
#      - 823766827 # Onedrive
#      - 975937182 # Fantastical 2 (purchase)
#      - 1088791669 # Kidslox
#      - 408981434 # iMovie
      - 409183694 # keynote
